export const FULL_PAYMENT ="FULL_PAYMENT";
export const APPROXIMATE_PAYMENT ="APPROXIMATE_PAYMENT";


export const FULL_PAYMENT_REQUEST = 'FULL_PAYMENT_REQUEST'
export const FULL_PAYMENT_SUCCESS = 'FULL_PAYMENT_SUCCESS'
export const FULL_PAYMENT_FAIL = 'FULL_PAYMENT_FAIL'
